dist: trusty
sudo: false
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
  - GOOGLETEST_HOME=$TRAVIS_BUILD_DIR/third_party/googletest
  - RAPIDASSIST_HOME=$TRAVIS_BUILD_DIR/third_party/RapidAssist
  - WIN32ARDUINO_HOME=$TRAVIS_BUILD_DIR

install:
- echo GOOGLETEST_HOME=$GOOGLETEST_HOME;
- echo RAPIDASSIST_HOME=$RAPIDASSIST_HOME;
- echo WIN32ARDUINO_HOME=$WIN32ARDUINO_HOME;
- cd $TRAVIS_BUILD_DIR/ci/ant

script:
- ant compile
- ant test
- ant demos

notifications:
  email: true
