dist: trusty
sudo: false
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
  - GOOGLETEST_HOME=$TRAVIS_BUILD_DIR/lib/googletest
  - RAPIDASSIST_HOME=$TRAVIS_BUILD_DIR/lib/RapidAssist
  - WIN32ARDUINO_HOME=$TRAVIS_BUILD_DIR

install:
- echo GOOGLETEST_HOME=$GOOGLETEST_HOME;
- echo RAPIDASSIST_HOME=$RAPIDASSIST_HOME;
- echo WIN32ARDUINO_HOME=$WIN32ARDUINO_HOME;

script:
- cd $TRAVIS_BUILD_DIR;
  mkdir build;
  cd build;
  cmake -DWIN32ARDUINO_BUILD_TEST=ON -DWIN32ARDUINO_BUILD_SAMPLES=ON ..
- make
- cd $TRAVIS_BUILD_DIR/build/bin;
  ./win32Arduino_unittest

notifications:
  email: true
