dist: trusty
sudo: required 
language: cpp
os:
- linux
branches:
  only:
  - make_install

script:
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./install_googletest.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./install_rapidassist.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./build_library.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis;
  ./build_buttonlibrary.sh;
- cd $TRAVIS_BUILD_DIR/build/bin;
  ./win32arduino_unittest || true; #do not fail build even if a test fails.

after_success:
- echo AFTER SUCCESS!

notifications:
  email: true
