dist: trusty
sudo: false
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
  - WIN32ARDUINO_HOME=$TRAVIS_BUILD_DIR
  - GOOGLETEST_HOME=$TRAVIS_BUILD_DIR/third_party/googletest-release-1.6.0

install:
- echo WIN32ARDUINO_HOME=$WIN32ARDUINO_HOME;
  echo GOOGLETEST_HOME=$GOOGLETEST_HOME;
- ant install

script:
- ant compile
- ant test
- ant demos

after_success:
- echo THIS IS AFTER SUCCESS!

notifications:
  email: true
