dist: trusty
sudo: false
language: cpp
os:
- linux
branches:
  only:
  - master
env:
  global:
  - PROJECT_NAME=test

before_install:
- cd $TRAVIS_BUILD_DIR/ci/ant;
  ant configure;
  source setupenv.sh;
install:
- echo THIRDPARTY_HOME=$THIRDPARTY_HOME;
  echo GOOGLETEST_HOME=$GOOGLETEST_HOME;
- ant install
script:
- cd $TRAVIS_BUILD_DIR/ci/ant;
  ant compile;
  ant test;
  ant demos;
after_success:
- echo THIS IS AFTER SUCCESS!

notifications:
  email: true
