# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
# version must contains build number to make sure that all commits are processed by appveyor.
# If build number is not part of the version than appveyor build fails with the following message: "Build version x.y.z already exists."
version: 2.1.0.{build}

# branches to build
branches:
  only:
    - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

environment:
  WIN32ARDUINO_HOME: $(APPVEYOR_BUILD_FOLDER)
  GOOGLETEST_HOME: $(APPVEYOR_BUILD_FOLDER)\third_party\googletest-release-1.6.0
  
# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

# clone directory
clone_folder: c:\projects\win32Arduino

# scripts that run after cloning repository
install:
- cmd: echo WIN32ARDUINO_HOME=%WIN32ARDUINO_HOME%
- cmd: echo GOOGLETEST_HOME=%GOOGLETEST_HOME%
- ps: .\ci\appveyor\prepare_github_deploy.ps1
- cmd: call .\ci\appveyor\ant_install.bat
- cmd: call ant -f .\ci\ant\build.xml install
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\install.bat
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\list_env_var.bat

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build_script:
- cmd: call ant -f .\ci\ant\build.xml compile
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
- cmd: call ant -f .\ci\ant\build.xml test
- cmd: call c:\projects\win32Arduino\ci\appveyor\upload_test_results.bat
- cmd: cd /d %APPVEYOR_BUILD_FOLDER%
- cmd: call ant -f .\ci\ant\build.xml demos

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: .\publish\win32Arduino_unittest.x86.release.xml
  name: win32ArduinoTest.x86.release.xml
  
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

#prepare deplying to github. See prepare_github_deploy.ps1 for more details.
deploy:
- provider: GitHub
  tag: $(GITHUB_TAG_NAME)
  release: $(GITHUB_RELEASE_NAME)
  description: Latest successful AppVeyor CI builds of branch '$(APPVEYOR_REPO_BRANCH)', commit $(APPVEYOR_REPO_COMMIT)
  auth_token:
    secure: BgyLisMc154qWpkyBdh8OD+D9HMM+YnBkh7H4MEUShKO3aCU+Fn/XVGJ07fTsRmH
  artifact: /(.*\.zip|.*\.exe)/
  draft: false           #true means release is private (visible to contributors only), false is public (visible to everyone)
  prerelease: false      #true for prerelease, false to identify this release as the 'latest release'
  force_update: true
